Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/AccountBankViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/BuyerViewModel.cs
Com.Danliris.Service.Sales.WebApi/Controllers/SpinningSalesContractController.cs
Com.Danliris.Service.Sales.WebApi/Controllers/WeavingSalesContractController.cs
Com.Danliris.Service.Sales.WebApi/Startup.cs
Com.Danliris.Service.Sales.WebApi/Utilities/APIEndpoint.cs

add pdf spinning and weaving, utilities API endpoint

add pdf spinning and weaving, utilities API endpoint

---

Com.Danliris.Service.Sales.Lib/Com.Danliris.Service.Sales.Lib.csproj

add itextsharp

---

Com.Danliris.Service.Sales.Lib/Com.Danliris.Service.Sales.Lib.csproj
Com.Danliris.Service.Sales.Lib/Migrations/20180629094838_updateSpinningSalesContractModel_addUOM.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20180629094838_updateSpinningSalesContractModel_addUOM.cs
Com.Danliris.Service.Sales.Lib/Models/Spinning/SpinningSalesContractModel.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelExportPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelExportPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/Utilities/NumberToTextEN.cs
Com.Danliris.Service.Sales.Lib/Utilities/NumberToTextIDN.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/AccountBankViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/AgentViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/BuyerViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/CurrencyViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Spinning/SpinningSalesContractViewModel.cs
Com.Danliris.Service.Sales.WebApi/Com.Danliris.Service.Sales.WebApi.csproj
Com.Danliris.Service.Sales.WebApi/Controllers/SpinningSalesContractController.cs
Com.Danliris.Service.Sales.WebApi/Controllers/WeavingSalesContractController.cs

add utility number to text ver en&id. add pdf eng ver

add utility number to text ver en&id. add pdf eng ver

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelExportPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelExportPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelPDFTemplate.cs

update pdf spinning and weaving

update pdf spinning and weaving

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/ProductionOrderPDFTemplate.cs

update pdf template Prodcution Order

update pdf template Prodcution Order

---

Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/FinishingPrintingProfiles/FinishingPrintingSalesContractDetailMapper.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/ProductionOrder/ProductionOrderLogic.cs
Com.Danliris.Service.Sales.Lib/SalesDbContext.cs
Com.Danliris.Service.Sales.Lib/ViewModels/ProductionOrder/ProductionOrderViewModel.cs
Com.Danliris.Service.Sales.WebApi/Controllers/ProductionOrderController.cs

update production order

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/GarmentMasterPlan/WeeklyPlanDataUtils/WeeklyPlanDataUtil.cs
Com.Danliris.Sales.Test/BussinesLogic/Facades/GarmentMasterPlan/WeeklyPlanFacadeTests/WeeklyPlanFacadeTest.cs
Com.Danliris.Sales.Test/BussinesLogic/Utils/BaseDataUtil.cs
Com.Danliris.Sales.Test/BussinesLogic/Utils/BaseFacadeTest.cs
Com.Danliris.Sales.Test/WebApi/Controllers/GarmentMasterPlan/WeeklyPlanControllerTests/WeeklyPlanControllerTest.cs
Com.Danliris.Sales.Test/WebApi/Utils/BaseControllerTest.cs
Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/GarmentMasterPlanProfiles/WeeklyPlanMapper.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentMasterPlan/WeeklyPlanFacades/WeeklyPlanFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Interface/GarmentMasterPlan/WeeklyPlanInterfaces/IWeeklyPlanFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentMasterPlan/WeeklyPlanLogics/WeeklyPlanLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20190214015411_WeeklyPlan.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20190214015411_WeeklyPlan.cs
Com.Danliris.Service.Sales.Lib/Migrations/SalesDbContextModelSnapshot.cs
Com.Danliris.Service.Sales.Lib/Models/GarmentMasterPlan/GarmentWeeklyPlanModels/WeeklyPlan.cs
Com.Danliris.Service.Sales.Lib/Models/GarmentMasterPlan/GarmentWeeklyPlanModels/WeeklyPlanItem.cs
Com.Danliris.Service.Sales.Lib/SalesDbContext.cs
Com.Danliris.Service.Sales.Lib/Utilities/BaseClass/BaseLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentMasterPlan/WeeklyPlanViewModels/WeeklyPlanItemViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentMasterPlan/WeeklyPlanViewModels/WeeklyPlanViewModel.cs
Com.Danliris.Service.Sales.WebApi/Com.Danliris.Service.Sales.WebApi.csproj
Com.Danliris.Service.Sales.WebApi/Controllers/GarmentMasterPlan/WeeklyPlanControllers/WeeklyPlanController.cs
Com.Danliris.Service.Sales.WebApi/Startup.cs

This reverts commit 841704dce0b4fb792054171d239c60b2d89408ad.

updated conflict merge

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/ProductionOrderPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelPDFTemplate.cs

edit satuan di cetakan sc spinning

SC Spinning pdf

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelPDFTemplate.cs

Update Cetakan SC Spinning

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/GarmentOmzetTargetDataUtils/GarmentOmzetTargetDataUtil.cs
Com.Danliris.Sales.Test/BussinesLogic/Facades/GarmentOmzetTargetTests/GarmentOmzetTargetTest.cs
Com.Danliris.Sales.Test/WebApi/Controllers/GarmentOmzetTargetControllerTest.cs
Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/GarmentOmzetTargetProfiles/GarmentOmzetTargetMapper.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentOmzetTargetFacades/GarmentOmzetTargetFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Interface/GarmentOmzetTargetInterface/IGarmentOmzetTarget.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentOmzetTargetLogics/GarmentOmzetTargetLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20191024093919_GarmentOmzetTarget.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20191024093919_GarmentOmzetTarget.cs
Com.Danliris.Service.Sales.Lib/Models/GarmentOmzetTargetModel/GarmentOmzetTargetModel.cs
Com.Danliris.Service.Sales.Lib/SalesDbContext.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentOmzetTargetViewModels/GarmentOmzetTargetViewModel.cs
Com.Danliris.Service.Sales.WebApi/Controllers/GarmentOmzetTargetController.cs
Com.Danliris.Service.Sales.WebApi/Startup.cs

Add Service, Unit Test & Create Table | Garment Omzet Target

Add Service & Create Table | Garment Omzet Target

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentByBuyer1ReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentByBuyer2ReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentByUnitReportFacade.cs

Update Facade | Report Cost Calculation

Update Facade | Report Cost Calculation

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentValidationReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentValidationReportLogic.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/CostCalculationGarmentBudgetPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/CostCalculationGarmentPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/GarmentSalesContractPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentValidationReportViewModel.cs

Update Service | Validasi RO Job Order  : DataUtils, Facade, Logic & ViewModels
Update PDF Templete : Cetakan Cost Calculation, Budget Export Garment, Sales Contract Garment

Update Service | Validasi RO Job Order & Update PDF Templete

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentByBuyer1ReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentByBuyer2ReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentByUnitReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentValidationReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/DetailCMGarmentByUnitReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/DistributionROGarmentReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/SMVGarmentByUnitReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/SMVGarmentByUnitReportLogic.cs

Update Logic & Facade | Garment Report

Update Facade | Report Garment

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/BudgetJobOrderDisplayFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentByBuyer1ReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentBySectionReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentByUnitReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/BudgetJobOrderDisplayLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Garment/BudgetJobOrderDisplayViewModel.cs

Update Service | Display Budget Job Order & Report Cost Calculation

Update Service | Display Budget Job Order & Report Cost Calculation

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/Garment_BudgetValidationPPICLogic.cs

Cost Calculation Approval - Kadiv Md - GPRItems IsUsed True only if ProductCode == "CLR001"

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/AvailableROReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/BudgetExportGarmentReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentApprovalReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/AvailableROReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/GarmentProductionOrderReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/ROGarmentLogics/ROGarmentLogic.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/CostCalculationGarmentBudgetPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/CostCalculationGarmentPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Garment/AvailableROReportViewModel.cs

Logic, Facade, ViewModels, DataUtils
PDF Templete

Update Sevice Report Garment

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/BudgetJobOrderDisplayFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/ProfitGarmentBySectionReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/BudgetJobOrderDisplayLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/ProfitGarmentBySectionReportViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Garment/BudgetJobOrderDisplayViewModel.cs

- Proft Garment By Section
- Display Budget Job Order / RO

Update Report Garment Service

---

Com.Danliris.Sales.Test/BussinesLogic/Facades/Garment/GarmentMerchandiser/CCGEmbroideryApprovalReportTest.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CCGEmbroideryApprovalReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/GarmentPurchasingQualityObjectiveReportLogic.cs

- Sasaran Mutu Penjualan Export Garment
- Validasi RO Job Order - Embroidery & Wash

Update Service Garment Report

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/AvailableROGarmentReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/AvailableROGarmentReportLogic.cs

- Profit Garment By Section
- Available RO Garment By Section

Update Logic & Facace - Garment Report

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/FinisihingPrintingSalesContract/FinisihingPrintingSalesContractDataUtil.cs
Com.Danliris.Sales.Test/BussinesLogic/DataUtils/ProductionOrder/ProductionOrderDataUtil.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/FinishingPrintingSalesContractPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelPDFTemplate.cs

PDF Templete SC DP, Spinnng, Weaving

Update PDF Templete

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/DOSales/DOSalesDataUtil.cs
Com.Danliris.Service.Sales.Lib/Migrations/20200928092627_Alter-Table-DoSales.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20200928092627_Alter-Table-DoSales.cs
Com.Danliris.Service.Sales.Lib/Models/DOSales/DOSalesModel.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/DOSalesPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/FinishingPrintingSalesContractPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/DOSales/DOSalesViewModel.cs

Enhancement PDF DO Sales & Sales Contract Textile

Enhancement PDF DO Sales & Sales Contract Textile

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/ProductionOrder/ProductionOrderDataUtil.cs
Com.Danliris.Sales.Test/ViewModels/ProductionOrder/ProductionOrderViewModelTest.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/DetailCMGarmentByUnitReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/FinishingPrinting/FinishingPrintingSalesContractLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/ProductionOrder/ProductionOrderLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20201125020112_Alter-Table-Sales-ProductionOrder.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20201125020112_Alter-Table-Sales-ProductionOrder.cs
Com.Danliris.Service.Sales.Lib/Models/ProductionOrder/ProductionOrderModel.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/ProductionOrderPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/ProductionOrder/ProductionOrderViewModel.cs

Add Options : Sales / Unit
Enhancement PDF Template Production Order

Enhancement - Production Order D/P

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs

Fixing Convert Excel Profit Garment Section Report

Enhancement - Profit Garment Section Report

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/DOAval/DOAvalFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/DOSales/DOSalesFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/DOStock/DOStockFacade.cs

Update DO Sales, DO Aval &  DO Stock

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/ProfitGarmentBySectionReportLogic.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/CostCalculationGarmentBudgetPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/CostCalculationGarmentPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/ProfitGarmentBySectionReportViewModel.cs

Add Column : Comission %, Profit IDR, Profit USD, Profit / FOB %

Enhancement Profit Garment By Section

---

Com.Danliris.Sales.Test/BussinesLogic/Facades/Garment/GarmentMerchandiser/ProfitGarmentBySectionReportTest.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs

Add Summary Uom & Amount on Profit Export Garment By Section

Enhancement - Garment Report

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentByComodityReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/ProfitGarmentByComodityReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/Garment_BudgetValidationPPICLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/ProfitGarmentByComodityReportViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/GarmentPurchaseRequestViewModel/GarmentPurchaseRequestViewModel.cs

- Excel Profit Garment By Section
- Excel Profit Garment By Comodity
- Add MDStaff Column Garment Budget Validation

Enhancement - G- Merchandiser

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentByComodityReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/ProfitGarmentBySectionReportFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/ProfitGarmentByComodityReportLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/Garment/Garment_BudgetValidationPPICLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/ProfitGarmentByComodityReportViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/IntegrationViewModel/GarmentPurchaseRequestViewModel/GarmentPurchaseRequestViewModel.cs

- Excel Profit Garment By Section
- Excel Profit Garment By Comodity
- Add MDStaff Column Garment Budget Validation

Enhancement - G-Merchandiser

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/AvailableROGarmentReportFacade.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/ROGarmentPdfTemplate.cs

Enhance PDF RO Garment

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/AvailableROGarmentReportFacade.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/ROGarmentPdfTemplate.cs

Enhancement - PDF RO garment

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/FinishingPrinting/FinishingPrintingSalesContractReportFacade.cs
Com.Danliris.Service.Sales.Lib/ViewModels/FinishingPrinting/FinishingPrintingSalesContractReportViewModel.cs

update sales dying and printing report

Update Sales (Dyeing & Printing) Report

---

Com.Danliris.Service.Sales.Lib/Models/Spinning/SpinningSalesContractModel.cs

Reverts danliris/com-danliris-service-sales#475

Revert "add BuyerJob in Buyer Model"

---

Com.Danliris.Service.Sales.Lib/ViewModels/FinishingPrinting/FinishingPrintingSalesContractViewModel.cs

Reverts danliris/com-danliris-service-sales#479

Revert "Enhance FinishingPrintingSalesContract"

---

Com.Danliris.Service.Sales.Lib/Migrations/20220624074459_Add-table-sales-contract-DP.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220624074459_Add-table-sales-contract-DP.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220624090023_Add-table-sales-contract-WV.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220624090023_Add-table-sales-contract-WV.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220624091957_Add-table-sales-contract-SP.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220624091957_Add-table-sales-contract-SP.cs
Com.Danliris.Service.Sales.Lib/Models/FinishingPrinting/FinishingPrintingSalesContractModel.cs
Com.Danliris.Service.Sales.Lib/Models/Spinning/SpinningSalesContractModel.cs
Com.Danliris.Service.Sales.Lib/Models/Weaving/WeavingSalesContractModel.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewFinishingPrintingSalesContractPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewSpinningSalesContractPdftemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewWeavingSalesContractPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/FinishingPrinting/FinishingPrintingSalesContractViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Spinning/SpinningSalesContractViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Weaving/WeavingSalesContractViewModel.cs

update pdf sc dying printing
update pdf sc weaving
update pdf sc spinning

update pdf sc

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/NewFinishingPrintingSalesContractPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/ViewModels/FinishingPrinting/FinishingPrintingSalesContractViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Spinning/SpinningSalesContractViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Weaving/WeavingSalesContractViewModel.cs

update sc pdf dp
update sc pdf wv
update sc pdf sp

update sc pdf

---

Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/SpinningProfiles/SpinningSalesContract.cs
Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/WeavingProfiles/WeavingSalesContract.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewFinishingPrintingSalesContractPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewSpinningSalesContractPdftemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewWeavingSalesContractPdfTemplate.cs
Com.Danliris.Service.Sales.WebApi/Controllers/SpinningSalesContractController.cs
Com.Danliris.Service.Sales.WebApi/Controllers/WeavingSalesContractController.cs

updated sc

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220727050251_Add-ApprovalCC-RO-On-GCC.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220727050251_Add-ApprovalCC-RO-On-GCC.cs
Com.Danliris.Service.Sales.Lib/Models/CostCalculationGarments/CostCalculationGarment.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentViewModel.cs

Add Approval Cost Calculation & RO Garment

Enhance - Cost Calculation Garment

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220818150624_Add-Column-Approval-Kadiv-On-CCG.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20220818150624_Add-Column-Approval-Kadiv-On-CCG.cs
Com.Danliris.Service.Sales.Lib/Models/CostCalculationGarments/CostCalculationGarment.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentViewModel.cs

Enhance - Cost Calculation Garment - PRD

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/NewWeavingSalesContractPdfTemplate.cs

updated product name, price separated, delivery schedule

udpate sc weaving

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentLogic.cs

change Hours from SMV CUtting to SMV Total

enhance-monitoringProductionStock-Bookeeping

---

Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/CostCalculationGarmentProfiles/CostCalculationGarmentMapper.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentBookingOrderFacade/GarmentBookingOrderFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Interface/GarmentBookingOrderInterface/IGarmentBookingOrder.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20221024022559_Add-Booking-Order-On-Cost-Calculation-Garment.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20221024022559_Add-Booking-Order-On-Cost-Calculation-Garment.cs
Com.Danliris.Service.Sales.Lib/Models/CostCalculationGarments/CostCalculationGarment.cs
Com.Danliris.Service.Sales.Lib/Models/GarmentBookingOrderModel/GarmentBookingOrderItem.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentBookingOrderViewModels/GarmentBookingOrderForCCGViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentBookingOrderViewModels/GarmentBookingOrderItemViewModel.cs
Com.Danliris.Service.Sales.WebApi/Controllers/GarmentBookingOrderController.cs

Enhance Cost Calculation Garment-PRD

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentBookingOrderViewModels/GarmentBookingOrderViewModel.cs

Update Booking Order Logic & Booking Order View Model

Update Logic & ViewModel

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/GarmentBookingOrderDataUtils/GarmentBookingOrderDataUtil.cs
Com.Danliris.Sales.Test/BussinesLogic/Facades/GarmentBookingOrderFacadeTest/GarmetBookingOrderFacadeTest.cs
Com.Danliris.Sales.Test/WebApi/Controllers/GarmentBookingOrderControllerTest.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentBookingOrderFacade/GarmentBookingOrderMonitoringFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentBookingOrderViewModels/GarmentBookingOrderMonitoringViewModel.cs

- modify query booking-order-report
- unit test booking order

enhance-booking-order-report

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentBookingOrderFacade/GarmentBookingOrderMonitoringFacade.cs

Enhance CCG And Report Booking Order

Enhance CCG And Report Booking Order

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentBookingOrderFacade/GarmentBookingOrderMonitoringFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs

Fix formula Remaining Qty Confirm

enhance monitoring booking order

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentBookingOrderFacade/GarmentBookingOrderMonitoringFacade.cs

Enhance Excel Monitoring Booking Order

Enhance Excel Monitoring Booking Order

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20221208072522_Modify-Cost-Calculation-Garment-Table.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20221208072522_Modify-Cost-Calculation-Garment-Table.cs
Com.Danliris.Service.Sales.Lib/Models/CostCalculationGarments/CostCalculationGarment.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentViewModel.cs
Com.Danliris.Service.Sales.WebApi/Startup.cs

modify vewmodel  ccg & logic bo

enhance ccg and bo

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/GarmentBookingOrderViewModels/GarmentBookingOrderForCCGViewModel.cs

Add Remark on List Booking Order

enhance cost calculation garment

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/CostCalculationGarmentBudgetPdfTemplate.cs

Enhance PDF Budget Garment

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/FinishingPrintingSalesContractExportPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewFinishingPrintingSalesContractPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewSpinningSalesContractPdftemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewWeavingSalesContractPdfTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/SpinningSalesContractModelExportPDFTemplate.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/WeavingSalesContractModelExportPDFTemplate.cs

PDF Sales Contract : Spinning, Weaving, Dyeing printing.

Enhance-PDF-Sales-Contract

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/CostCalculationGarmentProfiles/CostCalculationGarmentMapper.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentPreSalesContractLogics/GarmentPreSalesContractLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20230626072410_Add_Column_CCType_On_Tables_Cost_Calculation_Garment.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20230626072410_Add_Column_CCType_On_Tables_Cost_Calculation_Garment.cs
Com.Danliris.Service.Sales.Lib/Models/CostCalculationGarments/CostCalculationGarment.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentViewModel.cs

Add Option Subcon on Pre Sales Contract & Filter Subcon on Cost Calculation Garment

Enhance-Pre-SC-&-Cost-Calculation

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/GarmentSalesContractPDFTemplate.cs

Update PDF Garment Sales Contract Remark for Buyer Kurabo (K14)

Update PDF Garment Sales Contract DEV

---

Com.Danliris.Service.Sales.Lib/PDFTemplates/GarmentSalesContractPDFTemplate.cs

Update PDF Garment Sales Contract Remark for Buyer Kurabo (K14)

Update PDF Garment Sales Contract PRD

---

Com.Danliris.Sales.Test/BussinesLogic/Facades/ProductionOrder/ProductionOrderFacadeTest.cs
Com.Danliris.Sales.Test/WebApi/Controllers/ProductionOrderReportControllerTest.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs

Alhamdulillah Unit-Test Pertamaku

UNIT-TEST Dan Perbaikan bug filtering Sales

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs
Com.Danliris.Service.Sales.Lib/ViewModels/Report/ProductionOrderReportViewModel.cs

Penambahan Coloum Yang Kurang pada Export EIDP Button.

Bug Filtering Sales

---

Com.Danliris.Sales.Test/Com.Danliris.Sales.Test.csproj
Com.Danliris.Service.Sales.WebApi/Com.Danliris.Service.Sales.WebApi.csproj

<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>

MDP newDEV

---

Com.Danliris.Sales.Test/BussinesLogic/DataUtils/Garment/GarmentMerchandiser/CostCalculationGarmentDataUtil.cs
Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/CostCalculationGarmentProfiles/CostCalculationGarmentMapper.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentBookingOrderLogics/GarmentBookingOrderLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/GarmentPreSalesContractLogics/GarmentPreSalesContractLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20230626072410_Add_Column_CCType_On_Tables_Cost_Calculation_Garment.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20230626072410_Add_Column_CCType_On_Tables_Cost_Calculation_Garment.cs
Com.Danliris.Service.Sales.Lib/Models/CostCalculationGarments/CostCalculationGarment.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/CostCalculationGarmentViewModel.cs

Add Option Subcon on Pre Sales Contract & Filter Subcon on Cost Calculation Garment

Enhance-Pre-SC-&-Cost-Calculation - UAT

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs

MDP Bug Fix IEDP Tanggal Delivery.

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentSalesContractFacades/GarmentSalesContractFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ROGarment/ROGarmentFacade.cs

-Sales Contrace
-CC
-RO Garment

enhance-AddRollback

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/GarmentSalesContractFacades/GarmentSalesContractFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ROGarment/ROGarmentFacade.cs

-CC
-RO Garment
-SalesContract

enhance-FixRollback

---

Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/FinishingPrintingProfiles/FinishingSalesContractMapper.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewFinishingPrintingSalesContractPdfTemplate.cs

Enhance-SalesContract-DP-DEV

---

Com.Danliris.Service.Sales.Lib/AutoMapperProfiles/FinishingPrintingProfiles/FinishingSalesContractMapper.cs
Com.Danliris.Service.Sales.Lib/PDFTemplates/NewFinishingPrintingSalesContractPdfTemplate.cs

Enhance-SalesContract-DP-PRD

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/DetailCMGarmentByUnitReportLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/DetailCMGarmentByUnitReportViewModel.cs

enhance-report-cm-uat

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/DetailCMGarmentByUnitReportLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/DetailCMGarmentByUnitReportViewModel.cs

enhance-report-cm-dev

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/DetailCMGarmentByUnitReportLogic.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/DetailCMGarmentByUnitReportViewModel.cs

enhance-report-cm-prd

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs
Com.Danliris.Service.Sales.WebApi/Controllers/ProductionOrderReportController.cs

Fixing Parameter Report Production Order

2024/#16/Enhance-Report-Production-Order - DEV

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs
Com.Danliris.Service.Sales.WebApi/Controllers/ProductionOrderReportController.cs

Fixing Parameter Report Production Order

2024/#16/Enhance-Report-Production-Order - UAT

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ProductionOrder/ProductionOrderFacade.cs
Com.Danliris.Service.Sales.WebApi/Controllers/ProductionOrderReportController.cs

Fixing Parameter Report Production Order

2024/#16/Enhance-Report-Production-Order - PRD

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/LatestAvailableBudgetReportFacade.cs

Enhance XLS Laporan Kesiapan Budget

2024/#17/Enhance XLS Laporan Kesiapan Budget - DEV

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/Garment/Garment_BudgetValidationPPICFacade.cs
Com.Danliris.Service.Sales.Lib/SalesDbContext.cs

- Fix bug dimana saat approve kadivMd, Material Process terhapus.

2024/19/Fix/Remove-CaseCade Delete

---

Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/CostCalculationGarments/CostCalculationGarmentFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Facades/ROGarment/ROGarmentFacade.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Interface/CostCalculationGarmentLogic/ICostCalculationGarment.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/CostCalculationGarments/CostCalculationGarmentLogic.cs
Com.Danliris.Service.Sales.Lib/BusinessLogic/Logic/LogHistoryLogic.cs
Com.Danliris.Service.Sales.Lib/Migrations/20240910030817_add-coloum-Remark-LogHistory.Designer.cs
Com.Danliris.Service.Sales.Lib/Migrations/20240910030817_add-coloum-Remark-LogHistory.cs
Com.Danliris.Service.Sales.Lib/Models/LogHistoryModel/LogHistory.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/Cancel_Approval/CancelApprovalCostCalculationGarmentViewModel.cs
Com.Danliris.Service.Sales.Lib/ViewModels/CostCalculationGarment/Cancel_Approval/CancelApprovalCostCalculationReportViewModel.cs
Com.Danliris.Service.Sales.WebApi/Controllers/CostCalculationGarmentController.cs
Com.Danliris.Service.Sales.WebApi/Controllers/RO_GarmentsController.cs

2024/22/Fix/ReportCancelApproval
- enable search with ignore -isdelete
2024/20/Enhance/Add-Report-RejectRO
2024/20/Enhance/Add-Report-MonitoringCancelApprovalCCG
2024/19/Fix/Cancel-Approval-CC
- Fix cancel approval cc update data IsPRMaster,IsPosted material cc
2024/19/Fix/Remove-CaseCade Delete
- Fix bug dimana saat approve kadivMd, Material Process terhapus.
2024/19/Enhance/Add-Modul-Cancel-ApprovalCC

-Fix Error RoWithComponent
